version: '2'

networks:
  front:
    external: true
  back:
    external: true

volumes:
  elggdata:
    external: true

services:
  elgg:
    container_name: elgg
    build: .
    networks:
      - front
      - back
    volumes:
      - elggdata:/var/www/elgg
